version: "3.2"
services:
  socket-server:
    image: sessionclip/socket-server
    build:
      context: ./socket-server
      dockerfile: Dockerfile.prod
    links:
    - mongo
    - rabbitmq
    volumes:
    - ./socket-server:/app

  session-service:
    image: sessionclip/session-service
    build:
      context: ./session-service
      dockerfile: Dockerfile.prod
    links:
    - mongo
    volumes:
    - ./session-service:/app

  recordings-service:
    image: sessionclip/recordings-service
    build:
      context: ./recordings-service
      dockerfile: Dockerfile.prod
    links:
    - mongo
    - rabbitmq
    volumes:
    - ./recordings-service:/app

  web-agent:
    image: sessionclip/web-agent
    build:
      context: ./web-agent
      dockerfile: Dockerfile
      args:
      - API_HOST=connect.sessionclip.com
    links:
    - socket-server

  mongo:
    image: mongo:3.6.2

  rabbitmq:
    image: rabbitmq:3.7.7-management-alpine

  dashboard:
    image: sessionclip/dashboard
    build:
      context: ./dashboard-v2
      dockerfile: Dockerfile
      args:
      - ENV=production

  demo-site:
    image: sessionclip/demo-site
    build:
      context: ./demo-dashboard
      dockerfile: Dockerfile
      args:
      - ENV=production

  reverse-proxy:
    image: sessionclip/reverse-proxy
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    depends_on:
      - session-service
      - recordings-service
      - demo-site
      - dashboard
      - web-agent
      - socket-server
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=sessionclip.com
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/custom.conf > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
