version: "3.2"
services:
  socket-server:
    image: sessionclip/socket-server
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    links:
    - mongo
    - rabbitmq
    ports:
    - "8081:3000"
    volumes:
    - ./socket-server:/app

  dashboard:
    image: sessionclip/dashboard
    build:
      context: ./dashboard-v2
      dockerfile: Dockerfile
      args:
      - ENV=development

  demo-site:
    image: sessionclip/demo-site
    build:
      context: ./demo-dashboard
      dockerfile: Dockerfile
      args:
      - ENV=development

  session-service:
    image: sessionclip/session-service
    build:
      context: ./session-service
      dockerfile: Dockerfile
    links:
    - mongo
    ports:
    - "8082:3000"
    volumes:
    - ./session-service:/app

  recordings-service:
    image: sessionclip/recordings-service
    build:
      context: ./recordings-service
      dockerfile: Dockerfile
    links:
    - mongo
    - rabbitmq
    ports:
    - "8084:3000"
    volumes:
    - ./recordings-service:/app

  web-agent:
    image: sessionclip/web-agent
    build:
      context: ./web-agent
      dockerfile: Dockerfile
      args:
      - API_HOST=connect.sessionclip.localhost:8080
    links:
    - socket-server

  mongo:
    image: mongo:3.6.2
    ports:
    - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.7.7-management-alpine
    ports:
    - "15672:15672"

  reverse-proxy:
    image: sessionclip/reverse-proxy
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    depends_on:
      - session-service
      - recordings-service
      - web-agent
      - demo-site
      - socket-server
      - dashboard
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=sessionclip.localhost
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/custom.conf > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
