version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: docker-compose -f docker-compose.deploy.yml build --pull
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker-compose -f docker-compose.deploy.yml push
